services:
    qnx800-dev:
        privileged: true
        platform: "linux/amd64"
        image: qnx800
        container_name: qnx-build
        build:
            context: .
            # Don't rebuild dockerfile at all? exclude?
            # dockerfile: Dockerfile
        volumes:
            # Mount project to workspace --> Change in future so similar to sr7
            - ./:/workspace
            # Mounts
            # QNX License
            - "${HOME}/.qnx:/home/${USER}/.qnx"
            # QNX SDP
            - "${HOME}/qnx800:/home/${USER}/qnx800"
            # QNX Targets made by the toolchain --> mount to workspace
            - "${HOME}/qnxprojects:/workspace/qnxprojects"
            # SSH keys to build VM
            - "${HOME}/.ssh/:/home/${USER}/.ssh"
        working_dir: /workspace
        cap_add:
            - NET_ADMIN
        network_mode: host
        stdin_open: true
        tty: true